import React from "react";
import List from "./List.applications";

function ListContainer({ items }) {
  const listItems = [
    {
      id: 1,
      status: "underReview",
      company: "Google",
      title: "Software Engineer",
      updatedAt: new Date("2024-06-01"),
      createdAt: new Date("2024-05-15"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 2,
      status: "interview",
      company: "Amazon",
      title: "Front-End Developer",
      updatedAt: new Date("2024-06-05"),
      createdAt: new Date("2024-05-20"),
      bookmarked: true,
      selected: false,
    },
    {
      id: 3,
      status: "accepted",
      company: "Microsoft",
      title: "Back-End Developer",
      updatedAt: new Date("2024-06-10"),
      createdAt: new Date("2024-05-25"),
      bookmarked: false,
      selected: true,
    },
    {
      id: 4,
      status: "rejected",
      company: "Facebook",
      title: "Data Scientist",
      updatedAt: new Date("2024-06-15"),
      createdAt: new Date("2024-05-30"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 5,
      status: "underReview",
      company: "Apple",
      title: "Machine Learning Engineer",
      updatedAt: new Date("2024-06-20"),
      createdAt: new Date("2024-06-01"),
      bookmarked: true,
      selected: false,
    },
    {
      id: 6,
      status: "interview",
      company: "Netflix",
      title: "DevOps Engineer",
      updatedAt: new Date("2024-06-25"),
      createdAt: new Date("2024-06-05"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 7,
      status: "accepted",
      company: "Uber",
      title: "Full Stack Developer",
      updatedAt: new Date("2024-07-01"),
      createdAt: new Date("2024-06-10"),
      bookmarked: true,
      selected: true,
    },
    {
      id: 8,
      status: "rejected",
      company: "Airbnb",
      title: "Mobile Developer",
      updatedAt: new Date("2024-07-05"),
      createdAt: new Date("2024-06-15"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 9,
      status: "underReview",
      company: "Spotify",
      title: "Product Manager",
      updatedAt: new Date("2024-07-10"),
      createdAt: new Date("2024-06-20"),
      bookmarked: true,
      selected: false,
    },
    {
      id: 10,
      status: "interview",
      company: "Slack",
      title: "UI/UX Designer",
      updatedAt: new Date("2024-07-15"),
      createdAt: new Date("2024-06-25"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 11,
      status: "accepted",
      company: "Dropbox",
      title: "Security Engineer",
      updatedAt: new Date("2024-07-20"),
      createdAt: new Date("2024-07-01"),
      bookmarked: true,
      selected: true,
    },
    {
      id: 12,
      status: "rejected",
      company: "Twitter",
      title: "Database Administrator",
      updatedAt: new Date("2024-07-25"),
      createdAt: new Date("2024-07-05"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 13,
      status: "underReview",
      company: "LinkedIn",
      title: "Cloud Engineer",
      updatedAt: new Date("2024-07-30"),
      createdAt: new Date("2024-07-10"),
      bookmarked: true,
      selected: false,
    },
    {
      id: 14,
      status: "interview",
      company: "Salesforce",
      title: "QA Engineer",
      updatedAt: new Date("2024-08-01"),
      createdAt: new Date("2024-07-15"),
      bookmarked: false,
      selected: false,
    },
    {
      id: 15,
      status: "accepted",
      company: "Adobe",
      title: "Technical Writer",
      updatedAt: new Date("2024-08-05"),
      createdAt: new Date("2024-07-20"),
      bookmarked: true,
      selected: true,
    },
  ];

  return (
    <div className="flex flex-col w-full h-full bg-orange-500">
      <List items={items} />
    </div>
  );
}

export default ListContainer;
